language: java
jdk:
- oraclejdk8

before_install:

install: mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

after_success:
- codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml  --p

